# Tasmania Fishing Chatbot Configuration

# LLM Settings
llm:
  # Groq settings (llama models)
  groq:
    model: "llama-3.3-70b-versatile"
    temperature: 0.3
    max_tokens: 1024

  # Google Germini settings
  germini:
    model: "gemini-2.5-flash"
    temperature: 0.3
    max_tokens: 1024

  # Default LLM
  default_provider: "germini"


# RAG Settings
rag:
  # Text chunking settings
  chunk_size: 300     # Number of words per chunk
  chunk_overlap: 100   # Overlap between chunks
  top_k: 5            # Number of chunks to retrieve

  # Embedding model settings
  embedding:
    model: "all-MiniLM-L6-v2"   # Sentence transformer model

  # Vector database settings
  vector_db:
    name: "tas_fishing_docs"    # ChromaDB collection name
    type: "chromadb"

  
# Document Settings
documents:
  base_path: "./data"
  sources:
    - "tas_fishing_guide.json"



# Tool Settings
tools:
  # Weather API
  weather_api:
    enable: true
    api_key_env: "WEATHER_API_KEY"
    provider: "openweathermap"
    base_url: "https://api.openweathermap.org/data/2.5"


# UI Settings
ui:
  title: "Tasmania Fishing Information Assistant"
  description: "Get information about fishing regulations, locations, and species in Tasmania"
  theme: "soft"
  examples:
    - "What are the bag limits for brown trout?"
    - "Is a 26cm rainbow trout legal to keep?"
    - "Where can I fish for salmon in Tasmania?"
    - "What fishing license do I need?"
    - "What species can I catch at Great Lake?"
